[common.variables]  ############################################################

    worker_tag = "{{tag}}-worker"

[common]  ######################################################################

    # Application Key and Secret
    key = "<INSERT_APP_KEY_HERE>"  # <- ****************************************
    secret = "<INSERT_APP_SECRET_HERE>"  # <- **********************************

    namespace = "pyexamples-{{username}}"
    tag = "pyex-slurm-{{username}}"

[workerPool]  ##################################################################

    templateId = "<INSERT_COMPUTE_TEMPLATE_ID_OR_NAME_HERE>"  # <- ************
    imagesId = "yd-agent-slurm"

    workerPoolData = "wp_slurm.json"  # Defines the Slurm cluster properties
    workerTag = "{{worker_tag}}"

[workRequirement]  #############################################################

    taskType = "sbatch"
    workerTags = ["{{worker_tag}}"]

    inputs = ["sbatch-script.sh"]
    arguments = ["-N", "4", "{{wr_name}}/sbatch-script.sh"]
    outputs = ["*.out"]
    uploadTaskProcessOutput = true

    exclusiveWorkers = true

################################################################################
